#日志级别
logging:
    level:
     root: info
     org:
       springframework: debug



#多数据源配置学习=========================================
spring:
  datasource:
    one:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 2233d
      url: jdbc:mysql://10.82.13.208:3306/springboot_test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      #schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    two:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 2233d
      url: jdbc:mysql://10.82.13.208:3306/springboot_test2?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC


#mq配置=================================================
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

#邮箱发送服务器配置===============================================
  mail:
    host: 10.82.1.12
    port: 25
    password: infinova
    username: wugz@szinfinova.com
    default-encoding: UTF-8

#spring batch 批处理设置========================================
  batch:
    initialize-schema: always #自动执行建表sql
    job:
      enabled: false #关闭自动执行批处理操作

#学习使用=============================================
test.book:
  name: 三国演义
  version: 1.1
  price: 19.2
  others:
    - 足球
      coding
  books:
    book1:
      name: haha
      version: 1.2
      price: 12.4
      others:
        - qq
          ccc
    book2:
      name: xxx
      version: 1.3
      price: 20.3
      others:
        - dad
          dada
          adassdafasfsa