#日志级别
logging:
    level:
     root: info
     org:
       springframework: debug



#多数据源配置学习=========================================
spring:
  datasource:
    one:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/springboot-test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    two:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/springboot-test2?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC


#mq配置=================================================
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin




#学习使用=============================================
test.book:
  name: 三国演义
  version: 1.1
  price: 19.2
  others:
    - 足球
      coding
  books:
    book1:
      name: haha
      version: 1.2
      price: 12.4
      others:
        - qq
          ccc
    book2:
      name: xxx
      version: 1.3
      price: 20.3
      others:
        - dad
          dada
          adassdafasfsa